version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 8088:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test-user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: pass123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf  
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel